name: emma-olearn

services:
  # Azurite (Fake Azure Storage Service)
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    hostname: azurite
    restart: always
    command: "azurite --blobHost 0.0.0.0 --blobPort 10000 --queueHost 0.0.0.0 --queuePort 10001"
    ports:
      - "10000:10000"
      - "10001:10001"
      #- "10002:10002"
    networks:
      - olearn

  # One-time data population
  populate:
    image: kamk/azurite-populate
    env_file:
      - .env
    build:
      context: ./src/azurite_populate
      dockerfile: Dockerfile
    networks:
      - olearn
    depends_on:
      - azurite
    
  # Streamlit front-end
  front:
    image: kamk/flowerui
    env_file:
      - .env
    hostname: flowerui
    build:
      context: ./src/flowerui
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    networks:
      - olearn
    depends_on:
      populate:
        condition: service_completed_successfully

  # Streamlit front-end
  back:
    image: kamk/flowerpredict
    env_file:
      - .env
    hostname: flowerpredict
    build:
      context: ./src/flowerpredict
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    networks:
      - olearn
    depends_on:
      populate:
        condition: service_completed_successfully


networks:
  olearn: